name: Greenter Docs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -IU -r requirements.txt
    - name: Deploy Mkdocs
      run: |
        git config user.name "Giancarlos Salas";
        git config user.email "giansalex@gmail.com";
        git remote add gh-token "https://${GH_TOKEN}@github.com/thegreenter/docs.git";
        git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
        mkdocs gh-deploy -v --clean --remote-name gh-token --message "Deployed MkDocs";
      env:
        GH_TOKEN: ${{ secrets.ghToken }} 

